### ISSUE TITLE
6.X-5 metadata temporal attributes

### ISSUE THREAD

**Issue by rmalyankar** [IHO-S100WG/TSM8#13]
Proposal to add discovery metadata attributes to indicate temporal validity of dataset and availability of successor dataset. From S-104.

See the [proposal](https://github.com/IHO-S100WG/TSM8/tree/main/6.X-5%20Metadata%20temporal%20attributes) for details.

### Upated 25 Oct
Revised draft has just been uploaded, see the 25 October rev1 PDF on the proposal page.

**Comment by rmalyankar** [comment]
Spin-off thread for "closure" attribute in rev2 proposal here: #16

**Comment by DavidGrant-NIWC** [comment]
Recommend limitations of the proposed schema be noted in the proposal.

### Item 1
* XML **dateTime** format differs from ISO 8601:2004 and S-100 **DateTime**
  * What is the value of adding the XML format?
  * Recommend use the existing S-100 **DateTime** type for timeInstantBegin/End.
    * S-100 **DateTime** is restricted to complete representation, basic format.
* I think a spatio-temporal extent should be used, in harmony with Jonathan's proposal.
  * Supports use of **TruncatedDate**
  * Overcomes most limitations noted below.
* Strongly recommend adding the _temporalExtent_ attribute to the _dataCoverage_ rather than directly in **S100_DatasetDiscoveryMetadata**.
  * Note that a geographic extent is associated with each _dataCoverage_, not with each dataset.
  * **LIMITATION**: if left as proposed, there's no way to determine the interval of a specific _dataCoverage_ without downloading the data and examining the encoded dataset.
* Only a single temporal extent can be associated with the data (upper multiplicity is 1 vice *).
  * **LIMITATION**: Imposes discovery limitations, e.g., for seasonal publications (but not sure if there are / will be any of these types of datasets).
    * For example, a dataset that is intended to be used Jan-Mar and Jul-Sep
  *  Note that there can be multiple _boundingPolygons_ associated with each _dataCoverage_.
      *  It would be nice if each could have its own temporal extent.
* Since an instant (fully qualified date and time) must be specified for the begin and/or end:
  * **LIMITATION**: recurring instants such as "every Wednesday", or "the first of every month" can't be specified.
    * Strongly recommend this be noted in the proposal.
  * **LIMITATION**: If the dataset is to be used at a certain time of day, it will be necessary to update the metadata every day
    * e.g. 5pm-7pm can't be represented without also specifying a date.
* To provide updates to the discovery metadata, datasets must be published at the interval at which they _could_ be replaced, even if nothing changes.
  * **LIMITATION**: Suppose we want to publish two datasets, one for use M-F and another for use Sa-Su. The current schema requires updating the metadata every week, even if no data changes.

### ITEM 2
* Recommend using an instant vice a duration as noted in justification (3) of the proposal
![image](https://user-images.githubusercontent.com/62906211/137966826-0f35d021-c3de-459c-b764-0493df1e9248.png)
  * Duration is not used anywhere else in S-100
  * As proposed, every receiving system must compute the instant instead of computing it once at origination
  * Encoding software can automatically populate the instant.
    * No more error prone then populating the issue date.

### ITEM 3
* No need to add XML schema reference if proposal is updated to change both:
  *  Item 1 _timeInstantBegin/End_ type to **DateTime**
  * Item 2 duration is changed to an instant

**Comment by rmalyankar** [comment]
> > The ISO 8601 basic representation (20211019) is not an XML Schema built-in datatype and cannot be validated by XML Schema validation. XML Schema uses the ISO 8601 Extended Format. That format is also defined in ISO 8601, so the metadata is using an ISO format. See also S-100 3-9 (I can expand that clause to cover all date and time types and propose adding it to Part 1 too if desired).
> 
> * Use of an ISO format is not sufficient.
> * Use of alternate formats defined in 8601 is not allowed.
> * As you note, S-100 3-9 does not apply.
>   
>   * Even if updated, a mapping would need to be provided between the S-100 and XML types.
> * The fact that there is no XML built-in datatype type for an S-100 Date / DateTime is beside the point. There is also no built-in for TruncatedDate (or S-100 DateTime)
>   
>   * The restriction to use complete representation, basic format is not optional.
>   * The value can be encoded in an XML dateTime, but the document needs to be clear that the lexical representation must conform to the S-100 DateTime type, it cannot use the entire lexical space of the XML type.
>     
>     * Hence my recommendation to show as S-100 DateTime in the UML.
>     * The schema can implement using XML dateTime.

So let's see if I understand what you're saying. Your only objection is that the UML and table in the proposal say "dateTime" instead of "DateTime"?  The schemas can continue to encode date and date-time types as the XML built-in types xs:date and xs:dateTime?

> > [...] Also, the metadata group moved the geographic component boundingBox up from dataCoverage this summer (i.e., from class S100_DataCoverage to S100_DatasetDiscoveryMetadata), so it makes sense to put temporal extent for the dataset at the same level as bounding box. I suppose we could add temporal extent to S100_DataCoverage too, by analogy to boundingPolygon for the likely rare situations where it is different from that for the dataset. Can someone supply plausible examples for using it in S100_DataCoverage where it is different from the temporal extent of the dataset as a whole?
> 
> I'm fine with adding it to both dataset and _dataCoverage_.
> 
> Datasets containing multiple disjoint (in space and/or time) coverages should be considered. Moving _boundingBox_ makes the attribute less useful in these cases, but it probably doesn't matter because systems will just look at the required _boundingPolygon(s)_.
> 
> A single date-dependent feature in a single _dataCoverage_ can affect the temporal extent of the dataset, but does not necessarily affect the temporal extent of other _dataCoverages_. This may or may not be useful for optimizing data delivery, storage, and retrieval mechanisms.
> 
> > As the proposal explains, using duration is less susceptible to human error
> 
> We disagree on this point.
> 
> > and allows more fine tuning than date or date-time.
> 
> Sub-second resolution is not likely to be of any benefit, at least wrt to discovery metadata.

I wasn't talking about sub-second resolution. From the proposal:  _Zero components must be encoded if and only if they are significant for indicating the granularity of the start/end instants of the interval. A variation of ±X should be allowed for, where X is the component of smallest granularity._

> 
> > Duration is also an ISO type. In fact, given that some events should be triggered X time before another (e.g., notices due X hours before arrival), adding duration to Part 1 would be a good idea.
> 
> * The ISO model doesn't use duration in this exact use case (dataset publication interval).
> * Durations relative to instants are themselves specifying instants.
>   
>   * I'm not opposed to adding duration to Part 1, but recommend that it be a separate proposal, or part of Jonathan's proposal. It is not needed by this proposal.

We discussed the ISO use of duration in this use case during the metadata group meeting when Julia showed my slide with the ISO 19115-1 conceptual model for maintenance information. The ISO model of maintenance information does allow use of duration, specifically the ISO type TM_PeriodDuration.
